// <auto-generated />
using System;
using KidControl.Backend.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KidControl.Backend.Persistence.Migrations
{
    [DbContext(typeof(FleetDbContext))]
    [Migration("20260827165016_InitialFleetSchema")]
    partial class InitialFleetSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KidControl.Backend.Entities.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Label")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("label");

                    b.Property<long>("TelegramChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_chat_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_admin");

                    b.HasIndex("TenantId", "TelegramChatId")
                        .IsUnique()
                        .HasDatabaseName("ix_admin_tenant_id_telegram_chat_id");

                    b.ToTable("admin", (string)null);
                });

            modelBuilder.Entity("KidControl.Backend.Entities.Audit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("actor");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("DetailJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("detail_json");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_audit");

                    b.HasIndex("TenantId", "At")
                        .HasDatabaseName("ix_audit_tenant_id_at");

                    b.ToTable("audit", (string)null);
                });

            modelBuilder.Entity("KidControl.Backend.Entities.Command", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acked_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<string>("Result")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("result");

                    b.Property<DateTimeOffset>("TtlAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ttl_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_command");

                    b.HasIndex("DeviceId", "AckedAt")
                        .HasDatabaseName("ix_command_device_id_acked_at");

                    b.ToTable("command", (string)null);
                });

            modelBuilder.Entity("KidControl.Backend.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentVersion")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("agent_version");

                    b.Property<DateTimeOffset>("EnrolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrolled_at");

                    b.Property<string>("GroupLabel")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("group_label");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("OsInfo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("os_info");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean")
                        .HasColumnName("revoked");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_device");

                    b.HasIndex("LastSeenAt")
                        .HasDatabaseName("ix_device_last_seen_at");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_device_tenant_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_device_token_hash");

                    b.ToTable("device", (string)null);
                });

            modelBuilder.Entity("KidControl.Backend.Entities.DeviceDesired", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<bool>("ForceBlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("force_blocked");

                    b.Property<DateTimeOffset?>("NightBypassUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("night_bypass_until");

                    b.Property<bool>("Paused")
                        .HasColumnType("boolean")
                        .HasColumnName("paused");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("DeviceId")
                        .HasName("pk_device_desired");

                    b.ToTable("device_desired", (string)null);
                });

            modelBuilder.Entity("KidControl.Backend.Entities.DevicePolicy", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<bool>("IntervalsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("intervals_enabled");

                    b.Property<bool>("NightEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("night_enabled");

                    b.Property<TimeSpan>("NightEnd")
                        .HasColumnType("interval")
                        .HasColumnName("night_end");

                    b.Property<TimeSpan>("NightStart")
                        .HasColumnType("interval")
                        .HasColumnName("night_start");

                    b.Property<int>("PlayMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("play_minutes");

                    b.Property<int>("RestMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("rest_minutes");

                    b.Property<string>("TargetVersion")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("target_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("DeviceId")
                        .HasName("pk_device_policy");

                    b.ToTable("device_policy", (string)null);
                });

            modelBuilder.Entity("KidControl.Backend.Entities.DeviceStatus", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<bool>("IsNight")
                        .HasColumnType("boolean")
                        .HasColumnName("is_night");

                    b.Property<bool>("IsUnlimited")
                        .HasColumnType("boolean")
                        .HasColumnName("is_unlimited");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at");

                    b.Property<int>("ShutdownInSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("shutdown_in_seconds");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<TimeSpan>("TimeRemaining")
                        .HasColumnType("interval")
                        .HasColumnName("time_remaining");

                    b.HasKey("DeviceId")
                        .HasName("pk_device_status");

                    b.ToTable("device_status", (string)null);
                });

            modelBuilder.Entity("KidControl.Backend.Entities.EnrollCode", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("UsedByDeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("used_by_device_id");

                    b.HasKey("Code")
                        .HasName("pk_enroll_code");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_enroll_code_expires_at");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_enroll_code_tenant_id");

                    b.ToTable("enroll_code", (string)null);
                });

            modelBuilder.Entity("KidControl.Backend.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tenant");

                    b.ToTable("tenant", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000f1eef"),
                            Name = "Семья"
                        });
                });

            modelBuilder.Entity("KidControl.Backend.Entities.Admin", b =>
                {
                    b.HasOne("KidControl.Backend.Entities.Tenant", "Tenant")
                        .WithMany("Admins")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_admin_tenant_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("KidControl.Backend.Entities.Command", b =>
                {
                    b.HasOne("KidControl.Backend.Entities.Device", "Device")
                        .WithMany("Commands")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_command_device_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("KidControl.Backend.Entities.Device", b =>
                {
                    b.HasOne("KidControl.Backend.Entities.Tenant", "Tenant")
                        .WithMany("Devices")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_tenant_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("KidControl.Backend.Entities.DeviceDesired", b =>
                {
                    b.HasOne("KidControl.Backend.Entities.Device", "Device")
                        .WithOne("Desired")
                        .HasForeignKey("KidControl.Backend.Entities.DeviceDesired", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_desired_devices_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("KidControl.Backend.Entities.DevicePolicy", b =>
                {
                    b.HasOne("KidControl.Backend.Entities.Device", "Device")
                        .WithOne("Policy")
                        .HasForeignKey("KidControl.Backend.Entities.DevicePolicy", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_policy_device_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("KidControl.Backend.Entities.DeviceStatus", b =>
                {
                    b.HasOne("KidControl.Backend.Entities.Device", "Device")
                        .WithOne("Status")
                        .HasForeignKey("KidControl.Backend.Entities.DeviceStatus", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_status_device_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("KidControl.Backend.Entities.EnrollCode", b =>
                {
                    b.HasOne("KidControl.Backend.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enroll_code_tenant_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("KidControl.Backend.Entities.Device", b =>
                {
                    b.Navigation("Commands");

                    b.Navigation("Desired");

                    b.Navigation("Policy");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("KidControl.Backend.Entities.Tenant", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
